// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package tutorial

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	SelectAccount(ctx context.Context, id int64) (Account, error)
	SelectAccountForUpdate(ctx context.Context, id int64) (Account, error)
	SelectEntry(ctx context.Context, id int64) (Entry, error)
	SelectTransfer(ctx context.Context, id int64) (Transfer, error)
	SelectUser(ctx context.Context, username string) (User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
